version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    image: natev/recordlibbackend:latest
    ports: 
      - "8000:8000"
    networks:
      recordlib-net: 
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    image: natev/recordlibfrontend:latest
    ports:
      - "3000:80"
    networks: 
      recordlib-net: 
networks:
  recordlib-net: 