# Generated by Django 2.2.13 on 2020-12-02 17:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cleanslate', '0011_sourcerecord_raw_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='expungementpetitiontemplate',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='sealingpetitiontemplate',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='sourcerecord',
            name='court',
            field=models.CharField(blank=True, choices=[('CP', 'CP'), ('MDJ', 'MDJ'), ('MC', 'MC')], max_length=3),
        ),
    ]
