# Generated by Django 2.2.13 on 2020-12-03 15:46

import cleanslate.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleanslate', '0012_auto_20201202_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expungementpetitiontemplate',
            name='file',
            field=models.FileField(upload_to=cleanslate.models.set_template_path),
        ),
        migrations.AlterField(
            model_name='sealingpetitiontemplate',
            name='file',
            field=models.FileField(upload_to=cleanslate.models.set_template_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='expungement_petition_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expugement_template_user_profiles', to='cleanslate.ExpungementPetitionTemplate'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sealing_petition_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sealing_petition_template_user_profiles', to='cleanslate.SealingPetitionTemplate'),
        ),
    ]
