version: '3'
services:
  django_web:
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    image: natev/recordlib
    expose:
      - 8000
    ports: 
      - "8000:8000"
    networks:
      recordlib-net: 
    env_file:
      - .production.env
    depends_on:
      - migration
      - pg_db
    command: bash -c "python manage.py collectstatic && gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers 4"
  migration: 
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    image: natev/recordlib
    env_file: 
      - .production.env
    networks:
      recordlib-net:
    command: python manage.py migrate --noinput
    depends_on:
      - pg_db
  pg_db:
    build:
      context: .
      dockerfile: PG_Dockerfile
    restart: always
    env_file: 
      - .production.env
    networks:
      recordlib-net:
    expose:
      - "5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
networks:
  recordlib-net: 
volumes:
  dbdata: